[build]
  command = "pip install -r requirements.txt && python app.py"
  publish = "static"  # Ensure this matches the directory for static files

[build.environment]
  MISE_PYTHON_COMPILE = "false"
