[build]
  # Install your dependencies
  command = "pip install -r requirements.txt"
  # You might adjust the publish directory if needed
  publish = "templates"

[build.environment]
  # Force the use of precompiled Python to avoid build-time compilation issues
  MISE_PYTHON_COMPILE = "false"
